workflows:
  nexmusic_x_build:
    name: NexMusic X CI Build
    max_build_duration: 60

    environment:
      java: 17
      android_signing: false

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Fix Gradle permissions
        script: |
          chmod +x gradlew

      - name: Clean project
        script: |
          ./gradlew clean

      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug --stacktrace

    artifacts:
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - prince.ar.abdur.rahman2008@gmail.com
